import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],

  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Burger Hunt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="bg-base min-h-screen text-white">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
